  spring:
    application:
      name: komando
    datasource:
      url: jdbc:mysql://mysql:3306/komando_db
      username: root
      password: maysikwelpas
    jpa:
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
    jackson:
      date-format: MM dd, yyyy hh:mm a
      time-zone: GMT+08:00